# Generated by Django 4.1.4 on 2023-01-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=50)),
                ('cat', models.CharField(max_length=50)),
                ('isbn', models.IntegerField()),
                ('Aname', models.CharField(max_length=50)),
                ('active', models.IntegerField()),
            ],
        ),
    ]
