# Generated by Django 4.1.4 on 2023-01-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0002_alter_tickit_aname_alter_tickit_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickit',
            name='is_deleted',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
