# Generated by Django 4.1.4 on 2023-01-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_tickit_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickit',
            name='active',
        ),
    ]
