# Generated by Django 4.1.4 on 2023-01-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0004_remove_tickit_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickit',
            name='isbn',
        ),
    ]
