# Generated by Django 4.1.4 on 2023-01-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0005_remove_tickit_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickit',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
